backend:
  name: git-gateway
  branch: main

media_folder: 'public/assets/blog'
public_folder: '/assets/blog'
logo:
  src: https://https://rad-marshmallow-29c029.netlify.app/assets/blog/logo.svg
  show_in_header: true

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'src/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    sortable_fields:
      - 'title'
      - { field: 'date', default_sort: asc }
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Tags', name: 'tags', widget: 'list', default: ['post'] }
      - { label: 'Featured Image', name: 'image', widget: 'image' }
      - { label: 'Image caption', name: 'imageAlt', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
